### ISSUE TITLE
Red Squigglies in Editor show TS types as errors

### ISSUE THREAD

**Issue by e111077** [PolymerLabs/playground-elements#121]
When writing types in the editor in TS files, it shows a red squiggly under the type

![image](https://user-images.githubusercontent.com/5981958/112963149-ee0db980-90fb-11eb-8ae6-1de398385517.png)

**Comment by e111077** [comment]
Doing some weirdo things

![image](https://user-images.githubusercontent.com/5981958/112968806-8195b900-9101-11eb-916c-878d8fd02612.png)

**Comment by aomarks** [comment]
The `JSDoc types can only be used inside documentation comments` is actually a legit syntax error because the `!` should be on the property name instead of the type (`inputEl!: HTMLInputElement`). Pretty confusing tsc error, but not specific to playground.

The `Property 'dispatchEvent' does not exist on type 'CounterButton'.` error is because we don't have the `LitElement` typings loading in yet (tracking at https://github.com/PolymerLabs/playground-elements/issues/119). We shouldn't show it for now though --- adding that error code to the list of temporary exclusions in https://github.com/PolymerLabs/playground-elements/pull/122.
